# Generated by Django 5.2.1 on 2025-08-16 19:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('address', models.TextField(help_text='Full address of the event')),
                ('city', models.CharField(help_text='City where event is located', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/province', max_length=100)),
                ('country', models.CharField(default='United States', help_text='Country', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('open_time', models.TimeField(help_text='Event opening time')),
                ('close_time', models.TimeField(help_text='Event closing time')),
                ('start_date', models.DateField(help_text='Event start date')),
                ('end_date', models.DateField(help_text='Event end date')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_open', models.BooleanField(default=True, help_text='Whether the event is currently open')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the event is active/published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this event', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
