# Generated by Django 5.2.1 on 2025-08-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='General', help_text='Type/category of the event (e.g., Music, Sports, Food, Art, Business, Education)', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon identifier for the event (e.g., 'music-note', 'soccer-ball', 'utensils')", max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Whether the event is free to attend'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Event price (leave blank if free)', max_digits=10, null=True),
        ),
    ]
