# Generated by Django 5.2.1 on 2025-08-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_e285de_idx',
            old_name='notificatio_recipie_8b8b8b_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_f39341_idx',
            old_name='notificatio_recipie_9b9b9b_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_notific_a659f1_idx',
            old_name='notificatio_notific_0c0c0c_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_schedul_963ed3_idx',
            old_name='notificatio_schedule_1d1d1d_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='channels',
            field=models.JSONField(default=list, help_text='List of channels this notification was sent through'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data for the notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_reminder', 'Event Reminder'), ('event_update', 'Event Update'), ('event_cancellation', 'Event Cancellation'), ('new_event_nearby', 'New Event Nearby'), ('friend_invite', 'Friend Invite'), ('friend_accepted', 'Friend Accepted'), ('event_invite', 'Event Invite'), ('event_rsvp', 'Event RSVP'), ('system_announcement', 'System Announcement'), ('account_verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('security_alert', 'Security Alert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='in_app_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('event_reminder', 'Event Reminder'), ('event_update', 'Event Update'), ('event_cancellation', 'Event Cancellation'), ('new_event_nearby', 'New Event Nearby'), ('friend_invite', 'Friend Invite'), ('friend_accepted', 'Friend Accepted'), ('event_invite', 'Event Invite'), ('event_rsvp', 'Event RSVP'), ('system_announcement', 'System Announcement'), ('account_verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('security_alert', 'Security Alert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='email_body_template',
            field=models.TextField(blank=True, help_text='Template for email body'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='email_subject_template',
            field=models.CharField(blank=True, help_text='Template for email subject line', max_length=200),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='message_template',
            field=models.TextField(help_text='Template for notification message with placeholders'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('event_reminder', 'Event Reminder'), ('event_update', 'Event Update'), ('event_cancellation', 'Event Cancellation'), ('new_event_nearby', 'New Event Nearby'), ('friend_invite', 'Friend Invite'), ('friend_accepted', 'Friend Accepted'), ('event_invite', 'Event Invite'), ('event_rsvp', 'Event RSVP'), ('system_announcement', 'System Announcement'), ('account_verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('security_alert', 'Security Alert')], help_text='Type of notification this template is for', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='sms_template',
            field=models.CharField(blank=True, help_text='Template for SMS messages', max_length=160),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='title_template',
            field=models.CharField(help_text='Template for notification title with placeholders', max_length=200),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
